[build]
  publish = "."  
  functions = "netlify/functions"  

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[functions]
  node_bundler = "none"
  included_files = ["netlify/functions/claim.js", "netlify/functions/claim-history.js"]
